<?php

const POSTGRES_HOST = "%DBHOST%";
const POSTGRES_PORT = 5432;
const POSTGRES_DBNAME = "%DBNAME%";
const POSTGRES_USER = "%DBUSER%";
const POSTGRES_PASSWORD = "%DBPASSWORD%";


const UPDATER_CONTACT_EMAIL = "%UPDATER_EMAIL%";

const PRIVACY_CONTACT = "%PRIVACY_CONTACT%";
const PRIVACY_CONTACT_EMAIL = "%PRIVACY_EMAIL%";