<?php

const POSTGRES_HOST = "%DBHOST%";
const POSTGRES_PORT = 5432;
const POSTGRES_DBNAME = "%DBNAME%";
const POSTGRES_USER = "%DBUSER%";
const POSTGRES_PASSWORD = "%DBPASSWORD%";


const CONTACT_EMAIL = "%EMAIL%";